from enum import Enum

class RunStatus(Enum):
    STARTED = "STARTED"
    READING_SOURCE_DATA = "READING_SOURCE_DATA"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_VAL_WARN = "COMPLETED_WITH_VALIDATION_WARNING"
    COMPLETED_WITH_VAL_ERROR = "COMPLETED_WITH_VALIDATION_ERROR"
    COMPLETED_WITH_ZERO = "COMPLETED_WITH_ZERO"
    FAILED = "FAILED"
    ALREADY_COMPLETED = "ALREADY_COMPLETED"
    DUPLICATE_PARALLEL_START = "DUPLICATE_PARALLEL_START"

class ValidationRunStatus(Enum):
    ERROR = "VALIDATION_ERROR"
    WARNING = "VALIDATION_WARNING"
